GutReactor:
  digestion_efficiency: 0.94
  gastric_emptying_rate: 2.0
  absorption_delay: 8

LiverMetabolicRouter:
  glycogen_capacity: 130.0
  gluconeogenesis_rate: 1.8
  insulin_sensitivity: 0.92
  glucagon_sensitivity: 0.95

MuscleEffector:
  resting_atp_demand: 3.0
  exercise_factor: 5.0
  fat_utilization_rate: 0.7

HeartCirculation:
  cardiac_output: 6.2
  hormone_transport_delay: 0.6

BrainController:
  cortisol_threshold: 0.6
  stress_decay_rate: 0.09
  circadian_baseline: 1.2

SleepRegulationCenter:
  melatonin_release_rate: 0.38
  circadian_peak_time: 22
  sleep_drive_gain: 1.5

FatStorageReservoir:
  storage_efficiency: 0.85
  lipolysis_rate: 1.5

PancreaticValve:
  insulin_release_threshold: 5.0
  glucagon_release_threshold: 4.4

LungReactor:
  oxygen_uptake_rate: 350
  co2_exhale_rate: 280

KidneyFilter:
  urea_clearance: 60
  fluid_reabsorption: 0.97

SkinThermoregulator:
  sweat_rate_max: 2.0
  vasodilation_temp_threshold: 37.0
